version: '3.8'
services:
  db:
    image: postgres:12
    container_name: postgres
    user: $DOCKER_USER
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data/pgdata
    ports:
   
      - '5432:5432'
    expose:
 
      - '5432'
  odoo:
    image: odoo:15.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload

    volumes:
      - ${PWD}/odoo/addons:/mnt/extra-addons
      - ${PWD}/odoo/config:/etc/odoo
      - ${PWD}/odoo/log:/var/log/odoo/
      - ${PWD}/odoo/data:/var/lib/odoo
